# Generated by Django 3.0.7 on 2020-08-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_name', models.CharField(blank=True, default='', max_length=128)),
                ('fav_age', models.CharField(blank=True, default='', max_length=128)),
                ('fav_breed', models.CharField(blank=True, default='', max_length=128)),
                ('fav_url', models.TextField(blank=True, default='', max_length=128)),
                ('fav_image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
