# Generated by Django 3.0.7 on 2020-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='fav_image',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
